# Generated by Django 5.2.5 on 2025-10-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_unknown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('email', models.TextField(max_length=300)),
                ('message', models.TextField(max_length=800)),
            ],
        ),
    ]
