# Generated by Django 5.2.5 on 2025-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_unknown', '0003_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, verbose_name='Почта обзорщика'),
            preserve_default=False,
        ),
    ]
