# Generated by Django 5.2.4 on 2025-08-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
