# Generated by Django 5.2.5 on 2025-11-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagination_unknown', '0004_review_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SKU_code',
            new_name='sku_code',
        ),
    ]
