# Generated by Django 5.2.4 on 2025-09-02 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_casing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default=None, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='courses',
            name='length',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)], verbose_name='Продолжительность в часах'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)])),
                ('courses', models.ManyToManyField(to='test_casing.courses')),
            ],
        ),
        migrations.CreateModel(
            name='SubCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True, verbose_name='Наименование подраздела')),
                ('description', models.CharField(verbose_name='Описание раздела')),
                ('parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_casing.courses')),
            ],
        ),
    ]
